// using in server.js as ${list} and being accessed as list[index].property

let liszt = [
  {
    pid: 0,
    name: "api",
    pm2_env: {
      updateEnv: true,
      exit_code: 1,
      prev_restart_delay: 0,
      versioning: null,
      version: "1.0.0",
      unstable_restarts: 0,
      restart_time: 18,
      pm_id: 0,
      created_at: null,
      axm_dynamic: {},
      axm_options: [Object],
      axm_monitor: {},
      axm_actions: [],
      pm_uptime: 1645148999487,
      status: "errored",
      unique_id: "a67c52b1-cb74-4489-b2dd-02852906a9a7",
      VSCODE_GIT_ASKPASS_MAIN:
        "c:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
      VSCODE_GIT_ASKPASS_EXTRA_ARGS: "--ms-enable-electron-run-as-node",
      VSCODE_GIT_ASKPASS_NODE:
        "C:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
      GIT_ASKPASS:
        "c:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
      VSCODE_GIT_IPC_HANDLE: "\\\\.\\pipe\\vscode-git-0ac1a3a19f-sock",
      COLORTERM: "truecolor",
      LANG: "en_US.UTF-8",
      TERM_PROGRAM_VERSION: "1.64.2",
      TERM_PROGRAM: "vscode",
      windir: "C:\\Windows",
      VS160COMCOMNTOOLS:
        "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\",
      USERPROFILE: "C:\\Users\\Leif Christian",
      USERNAME: "Leif Christian",
      USERDOMAIN_ROAMINGPROFILE: "DESKTOP-193A42L",
      USERDOMAIN: "DESKTOP-193A42L",
      TMP: "C:\\Users\\LEIFCH~1\\AppData\\Local\\Temp",
      TEMP: "C:\\Users\\LEIFCH~1\\AppData\\Local\\Temp",
      SystemRoot: "C:\\Windows",
      SystemDrive: "C:",
      SESSIONNAME: "Console",
      PUBLIC: "C:\\Users\\Public",
      PSModulePath:
        "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
      PROMPT: "$P$G",
      ProgramW6432: "C:\\Program Files",
      "ProgramFiles(x86)": "C:\\Program Files (x86)",
      ProgramFiles: "C:\\Program Files",
      ProgramData: "C:\\ProgramData",
      PROCESSOR_REVISION: "6001",
      PROCESSOR_LEVEL: "23",
      PROCESSOR_IDENTIFIER: "AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD",
      PROCESSOR_ARCHITECTURE: "AMD64",
      PM2_PROGRAMMATIC: "true",
      PM2_JSON_PROCESSING: "true",
      PM2_INTERACTOR_PROCESSING: "true",
      PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW",
      Path: "C:\\Python310\\Scripts\\;C:\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Amazon\\AWSCLIV2\\;c:\\Program Files\\Postgresql\\13\\bin\\;c:\\Program Files\\Postgresql\\13\\;C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\Leif Christian\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Leif Christian\\AppData\\Roaming\\npm;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\Leif Christian\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Leif Christian\\.dotnet\\tools;C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Users\\Leif Christian\\AppData\\Local\\Programs\\mongosh\\",
      OS: "Windows_NT",
      ORIGINAL_XDG_CURRENT_DESKTOP: "undefined",
      OneDrive: "C:\\Users\\Leif Christian\\OneDrive",
      NVM_SYMLINK: "C:\\Program Files\\nodejs",
      NVM_HOME: "C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm",
      NUMBER_OF_PROCESSORS: "8",
      LOGONSERVER: "\\\\DESKTOP-193A42L",
      LOCALAPPDATA: "C:\\Users\\Leif Christian\\AppData\\Local",
      HOMEPATH: "\\Users\\Leif Christian",
      HOMEDRIVE: "C:",
      FPS_BROWSER_USER_PROFILE_STRING: "Default",
      FPS_BROWSER_APP_PROFILE_STRING: "Internet Explorer",
      DriverData: "C:\\Windows\\System32\\Drivers\\DriverData",
      ComSpec: "C:\\Windows\\system32\\cmd.exe",
      COMPUTERNAME: "DESKTOP-193A42L",
      CommonProgramW6432: "C:\\Program Files\\Common Files",
      "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
      CommonProgramFiles: "C:\\Program Files\\Common Files",
      CHROME_CRASHPAD_PIPE_NAME: "\\\\.\\pipe\\crashpad_10456_CAJZWLCPFFPBFYHW",
      ChocolateyLastPathUpdate: "132796511870128161",
      ChocolateyInstall: "C:\\ProgramData\\chocolatey",
      APPDATA: "C:\\Users\\Leif Christian\\AppData\\Roaming",
      ALLUSERSPROFILE: "C:\\ProgramData",
      PM2_HOME: "C:\\Users\\Leif Christian\\.pm2",
      api: "{}",
      NODE_APP_INSTANCE: 0,
      vizion_running: false,
      km_link: false,
      pm_pid_path: "C:\\Users\\Leif Christian\\.pm2\\pids\\api-0.pid",
      pm_err_log_path: "C:\\Users\\Leif Christian\\.pm2\\logs\\api-error.log",
      pm_out_log_path: "C:\\Users\\Leif Christian\\.pm2\\logs\\api-out.log",
      instances: 1,
      exec_mode: "fork_mode",
      exec_interpreter: "node",
      pm_cwd: "C:\\Users\\Leif Christian\\Desktop\\PM2 API",
      pm_exec_path: "C:\\Users\\Leif Christian\\Desktop\\PM2 API\\server.js",
      node_args: [],
      name: "api",
      env: [Object],
      merge_logs: true,
      vizion: true,
      autorestart: true,
      instance_var: "NODE_APP_INSTANCE",
      pmx: true,
      automation: true,
      treekill: true,
      username: "Leif Christian",
      windowsHide: true,
      kill_retry_time: 100,
      namespace: "default",
      node_version: "16.5.0",
      script: "server.js",
      watch: false,
      filter_env: [],
    },
    pm_id: 0,
    monit: { memory: 0, cpu: 0 },
  },
  {
    pid: 6172,
    name: "server",
    pm2_env: {
      kill_retry_time: 100,
      windowsHide: true,
      username: "Leif Christian",
      treekill: true,
      automation: true,
      pmx: true,
      instance_var: "NODE_APP_INSTANCE",
      watch: false,
      autorestart: true,
      vizion: true,
      merge_logs: true,
      env: [Object],
      namespace: "default",
      filter_env: [],
      name: "server",
      node_args: [],
      pm_exec_path: "C:\\Users\\Leif Christian\\Desktop\\PM2 API\\server.js",
      pm_cwd: "C:\\Users\\Leif Christian\\Desktop\\PM2 API",
      exec_interpreter: "node",
      exec_mode: "fork_mode",
      instances: 1,
      pm_out_log_path: "C:\\Users\\Leif Christian\\.pm2\\logs\\server-out.log",
      pm_err_log_path:
        "C:\\Users\\Leif Christian\\.pm2\\logs\\server-error.log",
      pm_pid_path: "C:\\Users\\Leif Christian\\.pm2\\pids\\server-1.pid",
      km_link: false,
      vizion_running: false,
      NODE_APP_INSTANCE: 0,
      ALLUSERSPROFILE: "C:\\ProgramData",
      APPDATA: "C:\\Users\\Leif Christian\\AppData\\Roaming",
      ChocolateyInstall: "C:\\ProgramData\\chocolatey",
      ChocolateyLastPathUpdate: "132796511870128161",
      CHROME_CRASHPAD_PIPE_NAME: "\\\\.\\pipe\\crashpad_10456_CAJZWLCPFFPBFYHW",
      CommonProgramFiles: "C:\\Program Files\\Common Files",
      "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
      CommonProgramW6432: "C:\\Program Files\\Common Files",
      COMPUTERNAME: "DESKTOP-193A42L",
      ComSpec: "C:\\Windows\\system32\\cmd.exe",
      DriverData: "C:\\Windows\\System32\\Drivers\\DriverData",
      FPS_BROWSER_APP_PROFILE_STRING: "Internet Explorer",
      FPS_BROWSER_USER_PROFILE_STRING: "Default",
      HOMEDRIVE: "C:",
      HOMEPATH: "\\Users\\Leif Christian",
      LOCALAPPDATA: "C:\\Users\\Leif Christian\\AppData\\Local",
      LOGONSERVER: "\\\\DESKTOP-193A42L",
      NUMBER_OF_PROCESSORS: "8",
      NVM_HOME: "C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm",
      NVM_SYMLINK: "C:\\Program Files\\nodejs",
      OneDrive: "C:\\Users\\Leif Christian\\OneDrive",
      ORIGINAL_XDG_CURRENT_DESKTOP: "undefined",
      OS: "Windows_NT",
      Path: "C:\\Python310\\Scripts\\;C:\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Amazon\\AWSCLIV2\\;c:\\Program Files\\Postgresql\\13\\bin\\;c:\\Program Files\\Postgresql\\13\\;C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm;C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\;C:\\Users\\Leif Christian\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Leif Christian\\AppData\\Roaming\\npm;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\Leif Christian\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Leif Christian\\.dotnet\\tools;C:\\Users\\Leif Christian\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Users\\Leif Christian\\AppData\\Local\\Programs\\mongosh\\",
      PATHEXT: ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW",
      PM2_USAGE: "CLI",
      PROCESSOR_ARCHITECTURE: "AMD64",
      PROCESSOR_IDENTIFIER: "AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD",
      PROCESSOR_LEVEL: "23",
      PROCESSOR_REVISION: "6001",
      ProgramData: "C:\\ProgramData",
      ProgramFiles: "C:\\Program Files",
      "ProgramFiles(x86)": "C:\\Program Files (x86)",
      ProgramW6432: "C:\\Program Files",
      PROMPT: "$P$G",
      PSModulePath:
        "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
      PUBLIC: "C:\\Users\\Public",
      SESSIONNAME: "Console",
      SystemDrive: "C:",
      SystemRoot: "C:\\Windows",
      TEMP: "C:\\Users\\LEIFCH~1\\AppData\\Local\\Temp",
      TMP: "C:\\Users\\LEIFCH~1\\AppData\\Local\\Temp",
      USERDOMAIN: "DESKTOP-193A42L",
      USERDOMAIN_ROAMINGPROFILE: "DESKTOP-193A42L",
      USERNAME: "Leif Christian",
      USERPROFILE: "C:\\Users\\Leif Christian",
      VS160COMCOMNTOOLS:
        "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\",
      windir: "C:\\Windows",
      TERM_PROGRAM: "vscode",
      TERM_PROGRAM_VERSION: "1.64.2",
      LANG: "en_US.UTF-8",
      COLORTERM: "truecolor",
      VSCODE_GIT_IPC_HANDLE: "\\\\.\\pipe\\vscode-git-1e0ed2593e-sock",
      GIT_ASKPASS:
        "c:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
      VSCODE_GIT_ASKPASS_NODE:
        "C:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
      VSCODE_GIT_ASKPASS_EXTRA_ARGS: "--ms-enable-electron-run-as-node",
      VSCODE_GIT_ASKPASS_MAIN:
        "c:\\Users\\Leif Christian\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
      PM2_HOME: "C:\\Users\\Leif Christian\\.pm2",
      unique_id: "52e03895-72bb-43d2-8214-faacfea34df6",
      status: "online",
      pm_uptime: 1645148976155,
      axm_actions: [Array],
      axm_monitor: [Object],
      axm_options: [Object],
      axm_dynamic: {},
      created_at: 1645148976155,
      pm_id: 1,
      restart_time: 0,
      unstable_restarts: 0,
      version: "1.0.0",
      versioning: null,
      node_version: "16.5.0",
    },
    pm_id: 1,
    monit: { memory: 38084608, cpu: 0.1 },
  },
];
